---
version: 0.2
env:
  shell: bash
phases:
  install:
    commands:
      - set -e
      - AWS_REGION=eu-central-1
      - DEFAULT_PATH=$(pwd)
      - TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
      - OUTPUT_PROFILE=shared
      - echo "Executing Pull Request on "
      - pip install cfn-lint
  build:
    commands:
      - echo "performing checks..."
      - cfn-lint --template *.yaml --regions $AWS_REGION
  post_build:
    commands:
      - echo "completed checks..."
artifacts:
  files:
    - '*'