customer:
  prefix: isp-ferrari-cicd
  description: CICD Components for Ferrari
  env: sss
  site: primary
  #components: cicd
  #expiration: ddmmyyyy
  #parentid: isp
  #parentname: IBM Sports
  #id: ferrari
  #landscape: pes
  #name: IBM Sports
  #program: pes
  #status: active
  #architecture: standard
  #orchestrator: codepipeline
  #built_by: terraform
  #compliance: null
  #data_classification: null
  target_account_id: "181579366464"
  iac_role_name: pesAutomationExecutionRole
  iac_version: 1.1
  zone:
    - az01
    - az02
    - az03
cloud:
  api_key: None
  default: 'yes'
  id: aw
  metadata: cloud.yaml
  name: AWS Cloud
  sites:
    - region: pr
      site: primary
      cloud_region: us-east-1
      zone:
        - data_center: use1az2
          default: true
          id: az01
          name: us-east-1a
        - data_center: use1az4
          id: az02
          name: us-east-1b
        - data_center: use1az6
          id: az03
          name: us-east-1c
  aws:
    deployou: true ### or false if ou exists
    deployaccount: true ### or false if account exists
    managedou: "dataplane-ou" ### Name of the ou for workload account
    accountname: "ibmsports-network" ### Name of the account
    accountid: "181579366464" ### Only required if deployaccount is false
    accountemail: "ibmsports-network@bg.vnet.ibm.com" ### Account owner email
    ownerfirstname: "Stephen" ### Account owner first name
    ownerlastname: "Hammer" ### Account owner last name
    account_customizations_name: "workload-customization" ### It must be a drop down list to choose from
environment:
  - id: prd
    name: Production
  - id: stg
    name: Staging
  - id: tst
    name: Testing
  - id: sec
    name: Security
  - id: dev
    name: Development
  - id: sss
    name: Shared Services
pipeline:
  shared: true
  deploy: true
  storage:
    buckets:
      - id: cp_bucket
        name: cp-bucket
        deploy: true
        force_destroy: false
        block_public_acls: true
        block_public_policy: true
        ignore_public_acls: true
        restrict_public_buckets: true
        versioning: Enabled
        bucket_encryption_algorithm: AES256
        tags:
          application: codepipeline
  iam:
    roles:
      - id: cp_svc_role
        deploy: true
        description: CodePipeline Service Role
        role_name: cp-svc-role
        assume_role_policy_file: cp_service_role.tpl
        tags:
          service: codepipeline
      - id: cb_svc_role
        deploy: true
        description: CodeBuild Service Role
        role_name: cb-svc-role
        assume_role_policy_file: cb_service_role.tpl
        tags:
          service: codebuild
      - id: iac_admin_role
        deploy: false
        description: IaC Admin Role
        role_name: pesAutomationExecutionRole
        assume_role_policy_file: iac_admin_role.tpl
        tags:
          service: IaC
    policy:
      - id: cp_svc_policy
        deploy: true
        role_name: cp_svc_role
        iac_role_name: pesAutomationExecutionRole
        policy_name: cp-svc-policy
        cp_artifact_bucket: cp_bucket
        shared_account: "181579366464"
        shared_account_role: ssm-read-role
        role_policy_file: cp_service_role_policy.tpl
      - id: cb_svc_policy
        deploy: true
        role_name: cb_svc_role
        iac_role_name: pesAutomationExecutionRole
        policy_name: cb-svc-policy
        cp_artifact_bucket: cp_bucket
        shared_account: "181579366464"
        shared_account_role: ssm-read-role
        role_policy_file: cb_service_role_policy.tpl
      - id: iac_admin_policy
        deploy: false
        role_name: iac_admin_role
        iac_role_name: pesAutomationExecutionRole
        policy_name: iac-admin-policy
        cp_artifact_bucket: cp_bucket
        shared_account: "181579366464"
        shared_account_role: ssm-read-role
        role_policy_file: iac-admin-role-policy.tpl
  codestar:
    - id: ghe_connection
      deploy: false
      create_codestar_connection: false
      codestar_connection_name: pes-isp-cs-conn-us-east-2
      tags:
        connection: github enterprise
      codestar_connection_host_name: ghe-host
      github_enterprise_url: https://github.ibm.com
      provider_type: GitHubEnterpriseServer
  codepipeline:
    - id: pipeline
      deploy: true
      cp_name: pipeline
      cp_service_role_name: cp_svc_role
      s3_bucket: cp_bucket
      stage:
        - name: source
          action:
            - name: source
              category: Source
              owner: AWS
              provider: CodeStarSourceConnection
              input_artifacts:
              output_artifacts:
                - infra-provisioning
              version: 1
              run_order: 1
              namespace: SOURCE
              codestar_connection: ghe_connection
              iac_repo_name: Platform-Engineering-Services/iac-pes-isp-wld-pes-network-us-east-2-pr
              iac_repo_branch_name: master
              outputartifactformat: CODE_ZIP
              detectchanges: true
              projectname:
              sns_topic:
              customdata:
              externalentityLink:
              configuration_file: source.json
        - name: tf_plan
          action:
            - name: plan0
              category: Build
              owner: AWS
              provider: CodeBuild
              input_artifacts:
                - infra-provisioning
              output_artifacts:
                - plan0
              version: 1
              run_order: 2
              namespace: PLAN
              projectname: tf_plan
              codestar_connection:
              iac_repo_name:
              iac_repo_branch_name:
              outputartifactformat:
              detectchanges:
              sns_topic:
              customdata:
              externalentityLink:
              configuration_file: plan0.json
            - name: plan1a
              category: Build
              owner: AWS
              provider: CodeBuild
              input_artifacts:
                - infra-provisioning
              output_artifacts:
                - plan1a
              version: 1
              run_order: 1
              namespace: PLAN
              projectname: tf_plan
              codestar_connection:
              iac_repo_name:
              iac_repo_branch_name:
              outputartifactformat:
              detectchanges:
              sns_topic:
              customdata:
              externalentityLink:
              configuration_file: plan1a.json
            - name: plan1b
              category: Build
              owner: AWS
              provider: CodeBuild
              input_artifacts:
                - infra-provisioning
              output_artifacts:
                - plan1b
              version: 1
              run_order: 1
              namespace: PLAN
              projectname: tf_plan
              codestar_connection:
              iac_repo_name:
              iac_repo_branch_name:
              outputartifactformat:
              detectchanges:
              sns_topic:
              customdata:
              externalentityLink:
              configuration_file: plan1b.json
            - name: plan2a
              category: Build
              owner: AWS
              provider: CodeBuild
              input_artifacts:
                - infra-provisioning
              output_artifacts:
                - plan2a
              version: 1
              run_order: 1
              namespace: PLAN
              projectname: tf_plan
              codestar_connection:
              iac_repo_name:
              iac_repo_branch_name:
              outputartifactformat:
              detectchanges:
              sns_topic:
              customdata:
              externalentityLink:
              configuration_file: plan2a.json
        - name: approval
          action:
            - name: approval
              category: Approval
              owner: AWS
              provider: Manual
              input_artifacts:
              output_artifacts:
              version: 1
              run_order: 3
              namespace: APPROVAL
              sns_topic: cp_sns_topic
              customdata: Please review and approve the terraform plan
              externalentityLink: #{PLAN.review_link}
              projectname:
              codestar_connection:
              iac_repo_name:
              iac_repo_branch_name:
              outputartifactformat:
              detectchanges:
              configuration_file: approval.json
        - name: tf_apply
          action:
            - name: apply0
              category: Build
              owner: AWS
              provider: CodeBuild
              input_artifacts:
                - infra-provisioning
              output_artifacts:
                - apply0
              version: 1
              run_order: 5
              namespace: APPLY
              projectname: tf_apply
              sns_topic:
              customdata:
              externalentityLink:
              codestar_connection:
              iac_repo_name:
              iac_repo_branch_name:
              outputartifactformat:
              detectchanges:
              configuration_file: apply0.json
            - name: apply1a
              category: Build
              owner: AWS
              provider: CodeBuild
              input_artifacts:
                - infra-provisioning
              output_artifacts:
                - apply1a
              version: 1
              run_order: 4
              namespace: APPLY
              projectname: tf_apply
              sns_topic:
              customdata:
              externalentityLink:
              codestar_connection:
              iac_repo_name:
              iac_repo_branch_name:
              outputartifactformat:
              detectchanges:
              configuration_file: apply1a.json
            - name: apply1b
              category: Build
              owner: AWS
              provider: CodeBuild
              input_artifacts:
                - infra-provisioning
              output_artifacts:
                - apply1b
              version: 1
              run_order: 4
              namespace: APPLY
              projectname: tf_apply
              sns_topic:
              customdata:
              externalentityLink:
              codestar_connection:
              iac_repo_name:
              iac_repo_branch_name:
              outputartifactformat:
              detectchanges:
              configuration_file: apply1b.json
            - name: apply2a
              category: Build
              owner: AWS
              provider: CodeBuild
              input_artifacts:
                - infra-provisioning
              output_artifacts:
                - apply2a
              version: 1
              run_order: 4
              namespace: APPLY
              projectname: tf_apply
              sns_topic:
              customdata:
              externalentityLink:
              codestar_connection:
              iac_repo_name:
              iac_repo_branch_name:
              outputartifactformat:
              detectchanges:
              configuration_file: apply2a.json
      tags:
  codebuild:
    - id: plan0
      deploy: true
      cb_project_name: plan0
      description: codebuild-project
      codebuild_timeout: 60
      cb_service_role_name: cb_svc_role
      iac_role_name: pesAutomationExecutionRole
      shared_account: "181579366464"
      shared_account_role: ssm-read-role
      artifacts_type: CODEPIPELINE
      compute_type: BUILD_GENERAL1_MEDIUM
      image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
      type: LINUX_CONTAINER
      image_pull_credentials_type: CODEBUILD
      tf_backend_role_name: tf-backend-role
      tf_backend_bucket_name: tf-backend
      tf_backend_encrypt: true
      tf_backend_dynamodb_name: tf-ddb-lock
      tf_s3_key: plan0.tfstate
      cloudwatch_log_group: cp_lg
      s3_bucket: cp_bucket
      build_spec_file: 0-plan.yml
      tags:
    - id: plan1a
      deploy: true
      cb_project_name: plan1a
      description: codebuild-project
      codebuild_timeout: 60
      cb_service_role_name: cb_svc_role
      iac_role_name: pesAutomationExecutionRole
      shared_account: "181579366464"
      shared_account_role: ssm-read-role
      artifacts_type: CODEPIPELINE
      compute_type: BUILD_GENERAL1_MEDIUM
      image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
      type: LINUX_CONTAINER
      image_pull_credentials_type: CODEBUILD
      tf_backend_role_name: tf-backend-role
      tf_backend_bucket_name: tf-backend
      tf_backend_encrypt: true
      tf_backend_dynamodb_name: tf-ddb-lock
      tf_s3_key: plan1a.tfstate
      cloudwatch_log_group: cp_lg
      s3_bucket: cp_bucket
      build_spec_file: 1a-plan.yml
      tags:
    - id: plan1b
      deploy: true
      cb_project_name: plan1b
      description: codebuild-project
      codebuild_timeout: 60
      cb_service_role_name: cb_svc_role
      iac_role_name: pesAutomationExecutionRole
      shared_account: "181579366464"
      shared_account_role: ssm-read-role
      artifacts_type: CODEPIPELINE
      compute_type: BUILD_GENERAL1_MEDIUM
      image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
      type: LINUX_CONTAINER
      image_pull_credentials_type: CODEBUILD
      tf_backend_role_name: tf-backend-role
      tf_backend_bucket_name: tf-backend
      tf_backend_encrypt: true
      tf_backend_dynamodb_name: tf-ddb-lock
      tf_s3_key: plan1b.tfstate
      cloudwatch_log_group: cp_lg
      s3_bucket: cp_bucket
      build_spec_file: 1b-plan.yml
      tags:
    - id: plan2a
      deploy: true
      cb_project_name: plan2a
      description: codebuild-project
      codebuild_timeout: 60
      cb_service_role_name: cb_svc_role
      iac_role_name: pesAutomationExecutionRole
      shared_account: "181579366464"
      shared_account_role: ssm-read-role
      artifacts_type: CODEPIPELINE
      compute_type: BUILD_GENERAL1_MEDIUM
      image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
      type: LINUX_CONTAINER
      image_pull_credentials_type: CODEBUILD
      tf_backend_role_name: tf-backend-role
      tf_backend_bucket_name: tf-backend
      tf_backend_encrypt: true
      tf_backend_dynamodb_name: tf-ddb-lock
      tf_s3_key: plan2a.tfstate
      cloudwatch_log_group: cp_lg
      s3_bucket: cp_bucket
      build_spec_file: 2a-plan.yml
      tags:
    - id: apply0
      deploy: true
      cb_project_name: apply0
      description: codebuild-project
      codebuild_timeout: 60
      cb_service_role_name: cb_svc_role
      iac_role_name: pesAutomationExecutionRole
      shared_account: "181579366464"
      shared_account_role: ssm-read-role
      artifacts_type: CODEPIPELINE
      compute_type: BUILD_GENERAL1_MEDIUM
      image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
      type: LINUX_CONTAINER
      image_pull_credentials_type: CODEBUILD
      tf_backend_role_name: tf-backend-role
      tf_backend_bucket_name: tf-backend
      tf_backend_encrypt: true
      tf_backend_dynamodb_name: tf-ddb-lock
      tf_s3_key: apply0.tfstate
      cloudwatch_log_group: cp_lg
      s3_bucket: cp_bucket
      build_spec_file: 0-apply.yml
      tags:
    - id: apply1a
      deploy: true
      cb_project_name: apply1a
      description: codebuild-project
      codebuild_timeout: 60
      cb_service_role_name: cb_svc_role
      iac_role_name: pesAutomationExecutionRole
      shared_account: "181579366464"
      shared_account_role: ssm-read-role
      artifacts_type: CODEPIPELINE
      compute_type: BUILD_GENERAL1_MEDIUM
      image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
      type: LINUX_CONTAINER
      image_pull_credentials_type: CODEBUILD
      tf_backend_role_name: tf-backend-role
      tf_backend_bucket_name: tf-backend
      tf_backend_encrypt: true
      tf_backend_dynamodb_name: tf-ddb-lock
      tf_s3_key: apply1a.tfstate
      cloudwatch_log_group: cp_lg
      s3_bucket: cp_bucket
      build_spec_file: 1a-apply.yml
      tags:
    - id: apply1b
      deploy: true
      cb_project_name: apply1b
      description: codebuild-project
      codebuild_timeout: 60
      cb_service_role_name: cb_svc_role
      iac_role_name: pesAutomationExecutionRole
      shared_account: "181579366464"
      shared_account_role: ssm-read-role
      artifacts_type: CODEPIPELINE
      compute_type: BUILD_GENERAL1_MEDIUM
      image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
      type: LINUX_CONTAINER
      image_pull_credentials_type: CODEBUILD
      tf_backend_role_name: tf-backend-role
      tf_backend_bucket_name: tf-backend
      tf_backend_encrypt: true
      tf_backend_dynamodb_name: tf-ddb-lock
      tf_s3_key: apply1b.tfstate
      cloudwatch_log_group: cp_lg
      s3_bucket: cp_bucket
      build_spec_file: 1b-apply.yml
      tags:
    - id: apply2a
      deploy: true
      cb_project_name: apply2a
      description: codebuild-project
      codebuild_timeout: 60
      cb_service_role_name: cb_svc_role
      iac_role_name: pesAutomationExecutionRole
      shared_account: "181579366464"
      shared_account_role: ssm-read-role
      artifacts_type: CODEPIPELINE
      compute_type: BUILD_GENERAL1_MEDIUM
      image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
      type: LINUX_CONTAINER
      image_pull_credentials_type: CODEBUILD
      tf_backend_role_name: tf-backend-role
      tf_backend_bucket_name: tf-backend
      tf_backend_encrypt: true
      tf_backend_dynamodb_name: tf-ddb-lock
      tf_s3_key: apply2a.tfstate
      cloudwatch_log_group: cp_lg
      s3_bucket: cp_bucket
      build_spec_file: 2a-apply.yml
      tags:
  cloudwatch:
    - id: cp_lg
      deploy: true
      cp_lg_name: cp-lg
      cp_lg_retention: 1
      tags:
        application: codepipeline
  tfbackend:
    - id: tf_backend
      deploy: true
      tf_backend_role_name: tf-backend-role
      tf_backend_role_policy_name: tf-backend-role-policy
      iac_role_name: pesAutomationExecutionRole
      tf_backend_role_tags:
        service: terraform
      tf_backend_bucket_name: tf-backend
      tf_backend_encrypt: true
      tf_backend_bucket_tags:
        application: tf backend
      tf_backend_dynamodb_name: tf-ddb-lock
      tf_backend_dynamodb_tags:
        application: tf backend
      tf_backend_region: us-east-1
      tf_s3_key: terraform.tfstate
  sns:
    topic:
      - id: cp_sns_topic
        deploy: true
        sns_topic_cp_name: cp-sns-topic
    subscriptions:
      - id: cp_sns_subscription
        deploy: true
        sns_topic_cp: cp_sns_topic
        sns_subscription_protocol: email
        endpoint_auto_confirms: true
        sns_topic_cp_subscriptions: frankie@ibm.com
